### PR TITLE
fixes to linting issues

### PR DESCRIPTION
**Pull request by casibbald**
## What did you implement:
Minor linting fixes

Closes: #41 

## How did you verify your change:
CI build

## What (if anything) would need to be called out in the CHANGELOG for the next release:

### CODE REVIEW

**Comment by vv9k** [comment]
Thank you for your contribution! I've let the CI run and there are still some linting errors. Would you be willing to fix them as well?

**Comment by casibbald** [comment]
> 

Yes I would love to get involved and fix as much as I can as I would like to use the project in my own opensource solution.

**Comment by casibbald** [comment]
@vv9k is there something limiting me from running actions in my own fork? I have loads of minutes I can use.
Could you lift the restriction for me?

**Comment by vv9k** [comment]
I think it doesn't allow autorun on first contribution, I'm not sure if I can adjust it. I looked but failed to find where to change it.

**Comment by vv9k** [comment]
Adjusted the settings, shouldn't ask now.

**Comment by casibbald** [comment]
@vv9k  Please take a look when you have a few free minutes, and approve if you are happy.

**Comment by vv9k** [comment]
Looks good to me! Thank you for clearing all linting issues :)

**Pull request merged**
